-- MySQL Script generated by MySQL Workbench
-- 03/15/17 12:07:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ad` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `Ad` ;

-- -----------------------------------------------------
-- Table `Ad`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ad`.`user` ;

CREATE TABLE IF NOT EXISTS `Ad`.`user` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ad`.`Ad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ad`.`Ad` ;

CREATE TABLE IF NOT EXISTS `Ad`.`Ad` (
  `ad_id` INT NOT NULL,
  `ad_type` VARCHAR(30) NULL,
  `click_num` INT NULL,
  PRIMARY KEY (`ad_id`),
  UNIQUE INDEX `ad_id_UNIQUE` (`ad_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ad`.`provience_click`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ad`.`provience_click` ;

CREATE TABLE IF NOT EXISTS `Ad`.`provience_click` (
  `provience` VARCHAR(20) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `ad_id` INT NOT NULL,
  `click_num` INT NULL,
  `proviencecol` VARCHAR(45) NULL,
  PRIMARY KEY (`provience`, `city`, `ad_id`),
  UNIQUE INDEX `provience_UNIQUE` (`provience` ASC),
  UNIQUE INDEX `city_UNIQUE` (`city` ASC),
  UNIQUE INDEX `ad_id_UNIQUE` (`ad_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ad`.`user_click`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ad`.`user_click` ;

CREATE TABLE IF NOT EXISTS `Ad`.`user_click` (
  `user_id` INT NOT NULL,
  `ad_id` INT NOT NULL,
  `click_num` INT NULL,
  `user_clickcol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`, `ad_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `ad_id_UNIQUE` (`ad_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
